name: ServerInfo
version: '1.0-SNAPSHOT'
main: cz.adaamn.serverInfo.ServerInfo
api-version: '1.21'

commands:
  sinfo:
    description: Shows server info
    permission: sinfo.use

  adam:
    description: Tajnej command

  zpravicka:
    description: Global message

permissions:
  sinfo.use:
    description: Allows user to execute /sinfo
    default: op
