name: ServerInfo
version: '1.0-SNAPSHOT'
main: cz.adaamn.serverInfo.ServerInfo
api-version: '1.21'

commands:
  sinfo:
    permission: sinfo.use
  jarvis:
  suitup:
  shoot:

permissions:
  sinfo.use:
    description: Allows user to execute /sinfo
    default: op
